# Generated by Django 3.1 on 2021-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_gotcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perstudentdata',
            name='Chemistry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perstudentdata',
            name='English',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perstudentdata',
            name='Level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perstudentdata',
            name='Mark',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perstudentdata',
            name='Math',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perstudentdata',
            name='NOQ',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perstudentdata',
            name='Physics',
            field=models.CharField(max_length=235, null=True),
        ),
    ]
