# Generated by Django 3.1 on 2021-02-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20201109_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allques',
            name='subjModel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='allques',
            name='teacherName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chemistryques',
            name='ans',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chemistryques',
            name='chemistryModel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chemistryques',
            name='teacherName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='englishques',
            name='ans',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='englishques',
            name='englishModel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='englishques',
            name='teacherName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mathques',
            name='ans',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mathques',
            name='mathModel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mathques',
            name='teacherName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicsques',
            name='ans',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='physicsques',
            name='physicsModel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='physicsques',
            name='teacherName',
            field=models.CharField(max_length=100),
        ),
    ]
